### ISSUE TITLE
Please remove dependencies

### ISSUE THREAD

**Issue by netvoip** [kotttee/pyrogram_patch#4]
I'm using pyrofork as a replacement for pyrogram, the original project is dead. Installing pyrogram as a dependency breaks pyrofork. Also redis package has version 5.x currently. It would be better to remove both dependencies.

**Comment by kotttee** [comment]
updated, try again please

**Comment by netvoip** [comment]
All good, thank you!
If possible, make it also available to install by pip. Thanks.
